# Site settings
# title: UltraNebula
email: matt@ma-jones.com
owner: UltraNebula
first_published: 2020
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://ultranebula.com" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown